### ISSUE TITLE
Report generation should use settings from shiny session for number of bootstrap samples etc

### ISSUE THREAD

**Issue by joethorley** [bcgov/shinyssdtools#163]

**Comment by sebdalgarno** [comment]
this is already implemented - did you see something that didn't match up?

**Comment by joethorley** [comment]
Great - the concern was the run time. And this is partly because calculating lots of HCx values using multi bootstrapping. Could switch to weighted bootstrap?

**Comment by joethorley** [comment]
We have switched to weighted bootstrap in the dev version of shinyssdtools to speed things up and as this will likely be the recommended method.
